### ISSUE TITLE
support same frameworks as parent package

### ISSUE THREAD

**Issue by jeremysimmons** [tailsu/Telerik.JustMock.Autofac#1]
support same frameworks as parent package
`portable-net4+sl5+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1` and `net40`

**Comment by tailsu** [comment]
Ok, so `net40` is easy. It's just a matter of adjusting the project properties, the nuspec and publishing the new version.

Portable, however, is not supported by JustMock itself, so that's a no-go.

**Comment by tailsu** [comment]
I updated the project to support net40, give it a go, and ping me back if you have any problems. Portable,  like I said, is going nowhere until JM itself goes portable.

**Comment by jeremysimmons** [comment]
@tailsu thanks. works fine. I don't need portable, and I understand why it wouldn't be supported.
