### ISSUE TITLE
MissingMethodException when using JustMock 2016.2.426.1 package

### ISSUE THREAD

**Issue by jeremysimmons** [tailsu/Telerik.JustMock.Autofac#2]
Test Name:  Fails_When_Using_AssemblyBinding
Test FullName:  UnitTestProject.JustMock2016_2_426_1.Fails_When_Using_AssemblyBinding
Test Source:    UnitTestProjectUsesBinding\JustMock2016_2_426_1.cs : line 14
Test Outcome:   Failed
Test Duration:  0:00:00.0786549

Result Message: 
Test method UnitTestProject.JustMock2016_2_426_1.Fails_When_Using_AssemblyBinding threw exception: 
System.MissingMethodException: Method not found: 'Void Telerik.JustMock.Mock.AssertAll(!!0)'.
Result StackTrace:  
at Telerik.JustMock.Autofac.MocksSource.AssertAll()
   at Telerik.JustMock.Autofac.AutomockContainerExtensions.AssertAll(IContainer container) in Telerik.JustMock.Autofac\AutomockContainerExtensions.cs:line 165
   at UnitTestProject.JustMock2016_2_426_1.Fails_When_Using_AssemblyBinding() in UnitTestProjectUsesBinding\JustMock2016_2_426_1.cs:line 16

Example based on [937d652](https://github.com/tailsu/Telerik.JustMock.Autofac/commit/937d6524dd6ecf5c0dce1e7390e86766a45919b8)

[Telerik.JustMock.Autofac-master.zip](https://github.com/tailsu/Telerik.JustMock.Autofac/files/397992/Telerik.JustMock.Autofac-master.zip)

**Comment by tailsu** [comment]
`System.MissingMethodException: Method not found: 'Void Telerik.JustMock.Mock.AssertAll(!!0)'.`

Looks like an old JM version. I'd guess the problem is that something was not properly rebuilt for the test.

Normally you don't get "method not found" exceptions, because almost all bindings are static and the compiler checks those for you. Maybe something didn't get recompiled when it had to?

**Comment by jeremysimmons** [comment]
@tailsu I'm far from normal... I always get the interesting problems.
Can you reproduce the issue with the attached project?
I want to be using the newer version of JM, but cannot because it's different than what Telerik.JustMock.Autofac is linked against, and seems to be what's causing the issue.

**Comment by jeremysimmons** [comment]
@tailsu the methods from these assemblies are definitely different.

[Mock.AssertAll(mock);](https://github.com/tailsu/Telerik.JustMock.Autofac/blob/master/Telerik.JustMock.Autofac/MocksSource.cs#L55) is what's causing the failure.

Adding an optional parameter affects binary compatibility. [System.MissingMethodException after adding an optional parameter](http://stackoverflow.com/a/9884700/26877)

![image](https://cloud.githubusercontent.com/assets/1406886/17344816/c00a2c4e-58c0-11e6-8f8a-f35e9dc92f56.png)

![image](https://cloud.githubusercontent.com/assets/1406886/17345137/dfc5ecb6-58c1-11e6-8d6b-cb0f3bf784c8.png)

**Comment by jeremysimmons** [comment]
Added this to MocksSource.cs and all tests pass.

```
private static MethodInfo _assertAll;

static MocksSource()
{
  _assertAll = (from mi in typeof(Mock).GetMethods()
     where mi.Name == "AssertAll"
     where mi.IsGenericMethodDefinition == true
     where mi.GetGenericArguments().Length == 1
     select mi
     ).FirstOrDefault();
}

public void AssertAll()
{
   foreach (var mock in mocks)
   {
    var mockAssertAllGeneric = _assertAll.MakeGenericMethod(mock.GetType());
    object[] args = new object[] { mock };
    if (mockAssertAllGeneric.GetParameters().Length == 2)
       args = new object[] { mock, null };
    try
    {
       mockAssertAllGeneric.Invoke(null, args);
    }
    catch (TargetInvocationException ex)
    {
       throw ex.InnerException;
    }
 }
}

```

I would like to have the library spec changed to have an upper limit on the version number
Telerik.JustMock, Version=2015.2.715.1 - AssertAll<T>(T mocked)

Then add a new version of this package - using this release as the dependency.
Telerik.JustMock, Version=2015.3.929.5 - AssertAll<T>(T mocked, string message = null)

and in the future - be aware that optional parameters break compatibility...

thanks for the awesome libraries!

**Comment by jeremysimmons** [comment]
I build a local nuget package against JustMock 2015.3.929.5, and no longer need to use the Reflection method above. Can I send you a pull request w/ the nuget package number incremented?

**Comment by tailsu** [comment]
Yes, please :)

**Comment by jeremysimmons** [comment]
roger that. will do.

**Comment by jeremysimmons** [comment]
@tailsu created pull request #3

**Comment by tailsu** [comment]
Great work!
